id: PEC3293BB
initial_creation_type: input
source_metadata:
  title: Adeu Rinpoche Series
  language: en
  description: 'Texts by and about the Eighth Trulshik Adeu Rinpoche, Druprik Khyuchok
    (''khrul zhig a lde''u grub rigs khyu mchog, 1931–2007), a senior Drukpa Kagyü
    master from Nangchen:'
  volume:
    19b73c8851b145eb913ce39aedc5b73d:
      title: Magnetizing (Wangdü) Prayer
      parent: Prayers
    35d5e5a47bb640a5839f8495614e270d:
      title: Prayer to Drukpa Kunley
      parent: Prayers
    2c7ee87d3ee244dba7c453399158eba8:
      title: Windhorse Practice of Tārā
      parent: Prayers
    265611ee7cac4ba991a077fe29bb9a3b:
      title: 'The Falling Rain of Blessings: A Brief Daily Practice of the Wealth
        Deity White Jambhala'
      parent: Sādhanas
created_at: '2022-02-28T22:34:23.464928'
last_modified_at: '2022-02-28T22:34:23.464935'
